services:
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "16672:15672"
      - "6672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - shared_net

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insights
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/master.sql:/docker-entrypoint-initdb.d/master.sql
      - ./database:/sql
      - ./database/data:/data
      - ./database/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: >
      postgres
      -c listen_addresses='*'
      -c hba_file=/etc/postgresql/pg_hba.conf
    networks:
      - shared_net

volumes:
  pgdata:
  rabbitmq_data:

networks:
  shared_net:
    name: shared_net