services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insights
    ports:
      - "5432:5432"
    volumes:
      - ./database/master.sql:/docker-entrypoint-initdb.d/master.sql
      - ./database:/sql
      - ./database/data:/data