services:
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "16672:15672"
      - "6672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - shared_net

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insights
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/master.sql:/docker-entrypoint-initdb.d/master.sql
      - ./database:/sql
      - ./database/data:/data
      - ./database/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: >
      postgres
      -c listen_addresses='*'
      -c hba_file=/etc/postgresql/pg_hba.conf
    networks:
      - shared_net

  sqlserver:
    image: sqlserver
    ports:
      - "11433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=MyStr0ng!Pass123
    volumes:
      - sqlserver_data:/var/opt/mssql
    entrypoint: [ "/bin/bash", "/usr/src/sql/entrypoint.sh" ]

volumes:
  pgdata:
  rabbitmq_data:
  sqlserver_data:

networks:
  shared_net:
    name: shared_net